apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.ingress.proxyConnectTimeout }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.ingress.proxySendTimeout }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.ingress.proxyReadTimeout }}"
    
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.pathPrefix }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "langchain-chatbot-denodo.fullname" . }}
            port:
              number: {{ .Values.service.port }}
